module.exports = Object.freeze({
    databaseError : "Database error!",
    noDataError : "Record not found!",
    badRequestMsg : "Bad Request!",
    emptyInput : "Please enter all values completely!",
    registerShareSuccess : "The share registered successfully!",
    traderIdError : "TraderId cannot be null!",
    registerAmountError : "Amount cannot be empty or negative value!",
    priceError : "Share price cannot be negative value!",
    portfolioError : "Share should be registered in the trader portfolio!",
    buySide : "BUY",
    sellSide : "SELL",
    traderBalanceError : "Trader balance is not enough for trading!",
    shareAmountError : "The share amount is not enough for trading!",
    registerShareError : "Share cannot registered!",
    tradeSideError : "Unsupported trade type!",
    idError : "Id cannot be null!",
    checkRegisteredShareError : "Share is not registered or does not belong to this trader!",
    updateRegisteredShareDateError : "You can only update the price once in hour!",
    updatePriceError : "Price cannot updated!",
    updateShareSuccessful : "The registered share updated successfully!",
    updateRegisteredShareError : "The registered share cannot updated!",
    registeredShareIdError : "The registered share ID cannot be null!",
    registeredShareBuySideError : "The selected share is not suitable for BUY!",
    registeredShareSellSideError : "The selected share is not suitable for SELL!",
    amountCheckError : "The amount to be purchased cannot exceed the entire share!",
    buyTradeSuccessful : "The BUY trade was successful!",
    tradeError : "Trade transaction failed!",
    successStatus : "SUCCESSFUL",
    failStatus : "FAILED",
    amountSellError : "The amount of shares you want to sell cannot be more than trader's own!", 
});